import Navbar from '@/components/Navbar';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import axios from 'axios';
import parse from 'html-react-parser'
import 'react-quill/dist/quill.snow.css';
import { AiFillEdit } from 'react-icons/ai';
import { AiFillDelete } from 'react-icons/ai';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Footer from '@/components/Footer';

export async function getServerSideProps(context) {
  try {
    const res = await axios.get(`${process.env.NEXT_PUBLIC_URL}/api/post`, { withCredentials: true });
    // console.log(res.data)

    return {
      props: {
        postData: res?.data || []
      }
    }
  } catch (error) {
    console.log(error);
    return {
      props: {
        postData: []
      }
    }
  }
}

export default function Home({ postData }) {

  const [user, setUser] = useState();

  useEffect(() => {
    setUser(JSON.parse(localStorage.getItem('user')));
  }, []);

  const date = (_date) => new Date(_date).toLocaleString('en', {
    year: "numeric",
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  });

  const navigate = useRouter();

  const deletePost = async (post_id) => {
    try {
      const res = await axios.delete(`${process.env.NEXT_PUBLIC_URL}/api/post/${post_id}`);

      navigate.replace(navigate.asPath);

    } catch (error) {
      console.log(error);
    }
  }

  return (
    <>
      <Head>
        <title>Blog Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-white'>
        <Navbar />

        {/* Home Page */}

        <div className="">
          <div className="grid gap-10 py-5 px-5 lg:px-20 ">
            {postData.map((post, i) => (
              <div className="home grid md:grid-flow-col md:grid-cols-2 gap-10 justify-center items-center"
                key={post.post_id} id={`post${i}`}>

                <div className="content">
                  <img
                    className='w-[100%] h-[20rem]'
                    src={`./uploads/posts/${post.post_img}`} alt="" />
                </div>

                <div className="content">
                  <h1 className='text-4xl font-bold'>{post.post_title}</h1>

                  <div className='h-36'>
                    <div className='hide-scroll overflow-auto text-lg ql-editor'>{parse(post.post_des)}</div>
                  </div>

                  <p className='text-lg'> <span>Posted By : </span>
                    {post.name}
                  </p>

                  <p className='text-lg mt-1'><span>Post Date : </span>
                    {date(post.post_date)}
                  </p>

                  {user ?
                    <div className='grid grid-cols-8 grid-flow-col text-3xl mt-2'>

                      <span className=''>
                        <Link
                          href={`/writePost/${post.post_id}`}
                          className='hover:text-[magenta]'> <AiFillEdit /> </Link>
                      </span>

                      <span
                        onClick={(e) => deletePost(post.post_id)}
                        className='hover:text-[magenta]'><AiFillDelete />
                      </span>
                    </div>

                    : <div> </div>
                  }

                </div>

              </div>
            ))}
          </div>
        </div>

      </div>

      <Footer />

    </>
  )
}
